# Site
site_name: Understanding India
copyright: '© Understanding India'
site_description: Understanding India - The content and newsletter for macro and nuanced understanding of socio political aspects of India.
site_author: Understanding India
site_url: https://understandingindia.github.io/site

# Repository
repo_name: Understanding India
repo_url: https://github.com/understandingindia/site
# edit_uri: blob/master/docs/


extra_css:
  - 'stylesheets/flexboxgrid.min.css'
  - 'stylesheets/extra.css'
  - 'https://use.fontawesome.com/releases/v5.4.2/css/all.css'
  - 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js"
  - "https://platform.twitter.com/widgets.js"
  - "js/extra-seq.js"
  - "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  - "https://code.jquery.com/jquery-3.3.1.min.js"

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: 'material'
  palette:
    primary: 'white'
    accent: 'indigo'
  favicon: 'img/favicon.ico'
  logo:
    icon: 'explore'
  feature:
    tabs: true

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  font:
    text: Monospace
    code: Monospace

pages:
  - Home: index.md
